### ISSUE TITLE
set "default" enum selection to something other than the element with a ZERO/0 value.

### ISSUE THREAD

**Issue by jarrodhroberson** [thediveo/enumflag#1]
I am trying to map log levels from an external library to a enum and what should be the sane `default` level of `INFO` is `4`, `DEBUG` is `0` and I can not find any other way to tell it which one to pick for the `default`

**Comment by thediveo** [comment]
Do you mean  something like `var colormode = ColorAuto`? Or do you mean default empty enum flag options?

That is, please have a look at the following code, which comes from my lxkns project, https://github.com/TheDiveO/lxkns/blob/1e9be3fb34ca6be7d6ff5617efbf0ec74eb685c0/cmd/internal/pkg/style/colormode.go#L73

Just for reference, this is the typical boilerplate, so we're on the same page: 

```go
// ColorMode is an enumeration for colorizing output always, auto(matic), and
// never.
type ColorMode enumflag.Flag

// Enumeration of allowed ColorMode values.
const (
	ColorAlways ColorMode = iota // always colorize
	ColorAuto                    // colorize if output goes to a terminal
	ColorNever                   // never colorize
)

// Defines the textual representations for the ColorMode values.
var colorModeIds = map[ColorMode][]string{
	ColorAlways: {"always", "on"},
	ColorAuto:   {"auto"},
	ColorNever:  {"never", "none", "off"},
}
```

And now we want `ColorAuto` to be the default, not `ColorAlways` (zero value), so I used the `NoOptDefVal` field of the github.com/spf13/cobra flag drop-in package:

```go
func ColorModeSetupCLI(rootCmd *cobra.Command) {
	rootCmd.PersistentFlags().VarP(
		enumflag.New(&colorize, "color", colorModeIds, enumflag.EnumCaseSensitive),
		"color", "c",
		"colorize the output; can be 'always' (default if omitted), 'auto',\n"+
			"or 'never'")
	rootCmd.PersistentFlags().Lookup("color").NoOptDefVal = "always"
}
```

**Comment by thediveo** [comment]
(that's actually a great question, so if that works for you, then I'll add the how-to set a non-zero default to the README.)

**Comment by jarrodhroberson** [comment]
This looks like what I wanted. I have an `enum` that represents some external values I am not in control of. Of course the most sensible default is `4` not `0`. I did not want to have to remap then and translate them every time. This looks like it will do what I need. I did not see anything like this when I was digging through the source code. Thanks for the timely response.

**Comment by thediveo** [comment]
I will document this in the README so its more prominent to find.
